class ContactDetailPage
  
  FORWARD_CONTACT_BUTTON_XPATH = ".//*[@value='Forward Contact']"
  CONTACT_DETAIL_NAME_XPATH = ".//*[@id='con2_ilecell']/div"
  CONTACT_DETAIL_SKILL_LIST_FIRST_XPATH = "(.//*[@class='list'])[last()]//tr[2]"
  CONTACT_DETAIL_SKILL_LIST_SECOND_XPATH = "(.//*[@class='list'])[last()]//tr[3]"
  CONTACT_DETAIL_RECORD_SKILL_LIST_FIRST_XPATH = "(.//*[@class='list'])[last()]//tr[2]//td[last()]/a"
  CONTACT_DETAIL_RECORD_SKILL_LIST_SECOND_XPATH = "(.//*[@class='list'])[last()]//tr[3]//td[last()]/a"
  CONTACT_DETAIL_APPLICATIONS_LIST_XPATH = "(.//*[@class='list'])[9]"
  CONTACT_DETAIL_BTN_ADD_SKILL_XPATH = ".//*[@id='topButtonRow']/input[9]"
  CONTACT_DETAIL_BTN_ADD_TO_LIST_XPATH = ".//*[@id='topButtonRow']/input[8]"
  CONTACT_DETAIL_BTN_APPLY_TO_JOB_XPATH = ".//*[@id='topButtonRow']/input[6]"
  CONTACT_DETAIL_BTN_NEW_EDUCATION_HIST_XPATH = ".//*[@value='New Education History']"
  CONTACT_DETAIL_BTN_NEW_EMPLOYMENT_HIST_XPATH = ".//*[@value='New Employment History']"
  CONTACT_DETAIL_BTN_NEW_UPDATE_RESUME_XPATH = ".//*[@name='ts2__resume_update']"
  CONTACT_DETAIL_BTN_EDIT_XPATH = ".//*[@name='edit']"
  CONTACT_DETAIL_BTN_DELETE_XPATH = ".//*[@name='del']"
  CONTACT_DETAIL_HOVER_LINKS_XPATH = ".//*[@class='listHoverLinks']"
  CONTACT_DETAIL_MAILING_ADDRESS_XPATH = ".//*[@id='con19_ileinner']/table/tbody/tr[1]/td"
  CONTACT_DETAIL_MAILING_ADDRESS_IE_XPATH = ".//*[@id='con19_ileinner']"
  CONTACT_DETAIL_COUNTRY_XPATH = ".//*[@id='00No0000008Htrx_ileinner']"
  CONTACT_DETAIL_APP_LIST_FIRST_XPATH = "((.//*[@class='bPageBlock brandSecondaryBrd secondaryPalette'])[9]//tr[2]//a)[3]"
  CONTACT_DETAIL_APP_LIST_SECOND_XPATH = "((.//*[@class='bPageBlock brandSecondaryBrd secondaryPalette'])[9]//tr[3]//a)[3]"
  CONTACT_DETAIL_APP_LIST_XPATH = "(.//*[@class='bPageBlock brandSecondaryBrd secondaryPalette'])[9]"
  CONTACT_DETAIL_JCARD_XPATH = ".//*[@class='jck-panel-header']"
  CONTACT_DETAIL_RESUME_IFRAME_ID = "066o0000002B6Ef"
  CONTACT_DETAIL_APP_LIST_FIRST_APP_XPATH = "(.//*[@class='bPageBlock brandSecondaryBrd secondaryPalette'])[9]//tr[2]/td[7]/a"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_XPATH = "(.//*[@class='list'])[3]"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_FIRST_XPATH = "(.//*[@class='list'])[3]//tr[2]"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_SECOND_XPATH = "(.//*[@class='list'])[3]//tr[3]"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_THIRD_XPATH = "(.//*[@class='list'])[3]//tr[4]"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_FOURTH_XPATH = "(.//*[@class='list'])[3]//tr[5]"
  CONTACT_DETAIL_NOTES_ATTACH_LIST_FIFTH_XPATH = "(.//*[@class='list'])[3]//tr[6]"
  CONTACT_DETAIL_EMPLOYMENT_LIST_XPATH = "(.//*[@class='list'])[10]"
  CONTACT_DETAIL_EMPLOYMENT_LIST_FIRST_NAME_XPATH = "(.//*[@class='list'])[10]//tr[2]/td[2]"
  CONTACT_DETAIL_EDUCATION_LIST_FIRST_XPATH = "(.//*[@class='list'])[9]//tr[2]/th/a"
  CONTACT_DETAIL_EMPLOYMENT_TITLE_1_XPATH = "(.//*[@class='detailList'])[1]//tr[9]/td[4]/div"
  CONTACT_DETAIL_DEGREE_NAME_1_XPATH = "(.//*[@class='detailList'])[1]//tr[12]/td[4]/div"
  
end